org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

mod_id=camilookup
mod_name=Cami LookUp
mod_version=0.1.0
mod_group=io.github.marcofallasu.camilookup
mod_authors=Marco Fallas Uma\u00f1a
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
forge_version=61.2.1
forge_version_range=[61,)
